--[[--

	Coffee Components was developed by @Coffilhg

	By using Coffee Components in your experience or application, you agree to either:
		1. Keep Attribute unchanged, or
		2. If an experience, to credit Coffee Components in your description, or in a
		   devforum post linked from your experience's description.

	V2 has involved over 70 hours of work to develop, so please consider supporting
	its development by reporting any issues or feedback you have at its repository:
	https://github.com/Coffilhg/Coffee-Components-Plugin

	You can get in touch with me on Discord via the social link here:
	https://create.roblox.com/store/asset/78239748407454/Coffee-Components

	Many thanks! ~ Coffilhg, November 10th 2025
	
--]]--

task.defer(function()
	local RunService = game:GetService("RunService")
	if not RunService:IsStudio() then
		print(`☕ Running CoffeeComponents [V2.1] by @Coffilhg`)
	end
end)

return {}